# Generated by Django 4.2.23 on 2025-12-04 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="category_img"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="product_img"),
                ),
                ("featured", models.BooleanField(default=True)),
                ("average_rating", models.FloatField(default=0.0)),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                (
                    "cateagory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
