# Generated by Django 4.2.23 on 2025-12-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="cateagory",
            new_name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default="Test"),
            preserve_default=False,
        ),
    ]
