# Generated by Django 4.2.23 on 2025-12-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("multicaixa", "Multicaixa Express"),
                    ("transferencia", "Transferência Bancária"),
                    ("dinheiro", "Dinheiro na Entrega"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
