# Generated by Django 4.2.23 on 2025-10-19 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0004_cart_unique_user_cart"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-id"]},
        ),
    ]
