# Generated by Django 4.2.23 on 2025-12-03 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0005_alter_product_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
